<?php

declare(strict_types=1);

namespace HelgeSverre\TurboVision\Examples\Studio;

use RuntimeException;

final class StudioPhpExporter
{
    public function generate(StudioProject $project): string
    {
        $components = array_map(
            static fn (StudioComponent $component): array => $component->toArray(),
            $project->components(),
        );
        $replacements = [
            '{{PROJECT_NAME}}' => var_export($project->name(), true),
            '{{PROJECT_WIDTH}}' => (string) $project->width(),
            '{{PROJECT_HEIGHT}}' => (string) $project->height(),
            '{{COMPONENTS}}' => var_export($components, true),
        ];

        return strtr($this->template(), $replacements);
    }

    public function save(string $path, StudioProject $project): void
    {
        $directory = dirname($path);
        if (! is_dir($directory)) {
            throw new RuntimeException("Export directory does not exist: {$directory}");
        }
        $temporary = tempnam($directory, '.studio-php-');
        if ($temporary === false) {
            throw new RuntimeException("Could not create a temporary export file in {$directory}.");
        }

        try {
            if (file_put_contents($temporary, $this->generate($project), LOCK_EX) === false
                || ! rename($temporary, $path)
            ) {
                throw new RuntimeException("Could not export generated PHP to {$path}.");
            }
        } finally {
            if (is_file($temporary)) {
                @unlink($temporary);
            }
        }
    }

    private function template(): string
    {
        return <<<'PHP'
<?php

declare(strict_types=1);

use HelgeSverre\TurboVision\Application\Application;
use HelgeSverre\TurboVision\Drawing\DrawBuffer;
use HelgeSverre\TurboVision\Events\Cmd;
use HelgeSverre\TurboVision\Events\Event;
use HelgeSverre\TurboVision\Events\EventType;
use HelgeSverre\TurboVision\Events\Key;
use HelgeSverre\TurboVision\Geometry\Rect;
use HelgeSverre\TurboVision\Menus\MenuBar;
use HelgeSverre\TurboVision\Menus\StatusLine;
use HelgeSverre\TurboVision\Views\Group;
use HelgeSverre\TurboVision\Views\State;
use HelgeSverre\TurboVision\Views\View;

$autoload = null;
$directory = __DIR__;
while (true) {
    $candidate = $directory . '/vendor/autoload.php';
    if (is_file($candidate)) {
        $autoload = $candidate;
        break;
    }
    $parent = dirname($directory);
    if ($parent === $directory) {
        break;
    }
    $directory = $parent;
}
if ($autoload === null) {
    fwrite(STDERR, "Could not find vendor/autoload.php.\n");
    exit(1);
}
require_once $autoload;

final class GeneratedStudioView extends View
{
    /** @var list<array{id:int,type:string,x:int,y:int,width:int,height:int,text:string}> */
    private const array COMPONENTS = {{COMPONENTS}};

    private const int PROJECT_WIDTH = {{PROJECT_WIDTH}};
    private const int PROJECT_HEIGHT = {{PROJECT_HEIGHT}};
    private const string PROJECT_NAME = {{PROJECT_NAME}};

    public function __construct(Rect $bounds)
    {
        parent::__construct($bounds);
        $this->options |= State::Selectable;
    }

    public function draw(): void
    {
        $width = $this->bounds->width();
        $height = $this->bounds->height();
        $this->fillRect(0, 0, $width, $height, ' ', 0x07);
        $originX = max(1, intdiv($width - self::PROJECT_WIDTH, 2));
        $originY = max(1, intdiv($height - self::PROJECT_HEIGHT, 2));

        foreach (self::COMPONENTS as $component) {
            $this->drawComponent($originX, $originY, $component);
        }

        $status = ' ' . self::PROJECT_NAME . '  •  Generated by Turbo Studio  •  Esc quits ';
        $this->writeClipped(0, max(0, $height - 1), $status, $width, 0x08);
    }

    public function handleEvent(Event $event): void
    {
        if ($event->what !== EventType::KeyDown) {
            return;
        }
        $key = $event->asKey();
        if ($key !== null && ($key->is(Key::Esc) || $key->is(Key::AltX) || strtolower($key->char) === 'q')) {
            if ($this->owner instanceof Group) {
                $this->owner->putEvent(Event::command(Cmd::Quit));
            }
            $this->clearEvent($event);
        }
    }

    /** @param array{id:int,type:string,x:int,y:int,width:int,height:int,text:string} $component */
    private function drawComponent(int $originX, int $originY, array $component): void
    {
        $x = $originX + $component['x'];
        $y = $originY + $component['y'];
        $width = $component['width'];
        $height = $component['height'];
        $text = $component['text'];

        switch ($component['type']) {
            case 'panel':
                if ($width > 2 && $height > 2) {
                    $this->fillRect($x + 1, $y + 1, $width - 2, $height - 2, ' ', 0x07);
                }
                $this->drawBox($x, $y, $width, $height, 0x08);
                $this->writeClipped($x + 2, $y, ' ' . $text . ' ', max(0, $width - 4), 0x0F);
                break;
            case 'label':
                $this->writeClipped($x, $y, $text, $width, 0x0F);
                break;
            case 'button':
                $label = '[ ' . $text . ' ]';
                $padding = max(0, $width - mb_strlen($label));
                $label = str_repeat(' ', intdiv($padding, 2)) . $label . str_repeat(' ', $padding - intdiv($padding, 2));
                $this->writeClipped($x, $y, $label, $width, 0x0B);
                break;
            case 'input':
                $this->writeClipped($x, $y, '› ' . str_pad($text, max(0, $width - 2), '·'), $width, 0x07);
                break;
            case 'list':
                $this->drawBox($x, $y, $width, $height, 0x08);
                foreach (explode('|', $text) as $index => $item) {
                    if ($index >= $height - 2) {
                        break;
                    }
                    $this->writeClipped($x + 2, $y + 1 + $index, ($index === 0 ? '› ' : '  ') . $item, max(0, $width - 3), $index === 0 ? 0x0B : 0x07);
                }
                break;
            case 'checkbox':
                $this->writeClipped($x, $y, '[x] ' . $text, $width, 0x0A);
                break;
            case 'separator':
                $this->fillRect($x, $y, $width, 1, '─', 0x08);
                break;
            case 'radio':
                $this->writeClipped($x, $y, '(o) ' . $text, $width, 0x0D);
                break;
            case 'progress':
                $percentage = max(0, min(100, (int) $text));
                $barWidth = max(1, $width - 7);
                $complete = (int) round($barWidth * $percentage / 100);
                $label = '['
                    . str_repeat('=', $complete)
                    . str_repeat('-', $barWidth - $complete)
                    . '] '
                    . str_pad((string) $percentage, 3, ' ', STR_PAD_LEFT)
                    . '%';
                $this->writeClipped($x, $y, $label, $width, 0x0E);
                break;
            case 'textarea':
                $this->drawBox($x, $y, $width, $height, 0x08);
                foreach (explode('|', $text) as $index => $line) {
                    if ($index >= $height - 2) {
                        break;
                    }
                    $this->writeClipped($x + 2, $y + 1 + $index, $line, max(0, $width - 4), 0x07);
                }
                break;
        }
    }

    private function drawBox(int $x, int $y, int $width, int $height, int $attr): void
    {
        if ($width < 2 || $height < 2) {
            return;
        }
        $this->fillRect($x + 1, $y, $width - 2, 1, '─', $attr);
        $this->fillRect($x + 1, $y + $height - 1, $width - 2, 1, '─', $attr);
        for ($row = $y + 1; $row < $y + $height - 1; $row++) {
            $this->writeClipped($x, $row, '│', 1, $attr);
            $this->writeClipped($x + $width - 1, $row, '│', 1, $attr);
        }
        $this->writeClipped($x, $y, '┌', 1, $attr);
        $this->writeClipped($x + $width - 1, $y, '┐', 1, $attr);
        $this->writeClipped($x, $y + $height - 1, '└', 1, $attr);
        $this->writeClipped($x + $width - 1, $y + $height - 1, '┘', 1, $attr);
    }

    private function fillRect(int $x, int $y, int $width, int $height, string $char, int $attr): void
    {
        if ($width <= 0 || $height <= 0) {
            return;
        }
        $buffer = new DrawBuffer($width);
        $buffer->moveChar(0, $char, $attr, $width);
        for ($row = 0; $row < $height; $row++) {
            $this->writeLine($x, $y + $row, $width, 1, $buffer);
        }
    }

    private function writeClipped(int $x, int $y, string $text, int $width, int $attr): void
    {
        if ($width <= 0 || $y < 0 || $y >= $this->bounds->height()) {
            return;
        }
        $text = preg_replace('/[\x00-\x1F\x7F]/u', ' ', $text) ?? '';
        $this->writeStr($x, $y, mb_substr($text, 0, $width), $attr);
    }
}

final class GeneratedStudioApp extends Application
{
    private ?GeneratedStudioView $generatedView = null;

    protected function initMenuBar(Rect $bounds): ?MenuBar
    {
        return null;
    }

    protected function initStatusLine(Rect $bounds): ?StatusLine
    {
        return null;
    }

    protected function layout(): void
    {
        $bounds = Rect::of(0, 0, $this->screenObj->cols(), $this->screenObj->rows());
        $this->setBounds($bounds);
        $this->children = [];
        $this->currentView = null;
        $this->desktop = null;
        $this->menuBar = null;
        $this->statusLine = null;
        $this->generatedView = new GeneratedStudioView($bounds);
        $this->insert($this->generatedView);
        $this->setCurrent($this->generatedView);
    }

    public function reflowDesktop(): void
    {
        $bounds = Rect::of(0, 0, $this->screenObj->cols(), $this->screenObj->rows());
        $this->setBounds($bounds);
        $this->generatedView?->changeBounds($bounds);
    }
}

exit((new GeneratedStudioApp())->run());
PHP;
    }
}
